// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Srikaran.ARFlights.Data.Writer;

namespace Srikaran.ARFlights.Data.Writer.Migrations
{
    [DbContext(typeof(FlightsDBContext))]
    partial class FlightsDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0-preview.18572.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Srikaran.ARFlights.DomainEntities.Booking", b =>
                {
                    b.Property<long>("BookingId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("BookingDate");

                    b.Property<string>("FlightNo");

                    b.Property<int>("PassengerId");

                    b.HasKey("BookingId");

                    b.HasIndex("PassengerId");

                    b.ToTable("Bookings");

                    b.HasData(
                        new
                        {
                            BookingId = 1L,
                            BookingDate = new DateTime(2019, 2, 2, 0, 0, 0, 0, DateTimeKind.Local),
                            FlightNo = "QA11",
                            PassengerId = 111
                        },
                        new
                        {
                            BookingId = 11L,
                            BookingDate = new DateTime(2019, 2, 2, 0, 0, 0, 0, DateTimeKind.Local),
                            FlightNo = "QA11",
                            PassengerId = 112
                        },
                        new
                        {
                            BookingId = 2L,
                            BookingDate = new DateTime(2019, 2, 2, 0, 0, 0, 0, DateTimeKind.Local),
                            FlightNo = "VM24",
                            PassengerId = 113
                        },
                        new
                        {
                            BookingId = 12L,
                            BookingDate = new DateTime(2019, 2, 2, 0, 0, 0, 0, DateTimeKind.Local),
                            FlightNo = "QA201",
                            PassengerId = 114
                        },
                        new
                        {
                            BookingId = 3L,
                            BookingDate = new DateTime(2019, 2, 2, 0, 0, 0, 0, DateTimeKind.Local),
                            FlightNo = "QA201",
                            PassengerId = 115
                        },
                        new
                        {
                            BookingId = 13L,
                            BookingDate = new DateTime(2019, 2, 3, 0, 0, 0, 0, DateTimeKind.Local),
                            FlightNo = "QA11",
                            PassengerId = 116
                        },
                        new
                        {
                            BookingId = 4L,
                            BookingDate = new DateTime(2019, 2, 2, 0, 0, 0, 0, DateTimeKind.Local),
                            FlightNo = "VM24",
                            PassengerId = 117
                        },
                        new
                        {
                            BookingId = 14L,
                            BookingDate = new DateTime(2019, 2, 3, 0, 0, 0, 0, DateTimeKind.Local),
                            FlightNo = "QA201",
                            PassengerId = 118
                        },
                        new
                        {
                            BookingId = 5L,
                            BookingDate = new DateTime(2019, 2, 3, 0, 0, 0, 0, DateTimeKind.Local),
                            FlightNo = "VM24",
                            PassengerId = 119
                        },
                        new
                        {
                            BookingId = 15L,
                            BookingDate = new DateTime(2019, 2, 4, 0, 0, 0, 0, DateTimeKind.Local),
                            FlightNo = "QA11",
                            PassengerId = 120
                        },
                        new
                        {
                            BookingId = 6L,
                            BookingDate = new DateTime(2019, 2, 3, 0, 0, 0, 0, DateTimeKind.Local),
                            FlightNo = "VM24",
                            PassengerId = 121
                        },
                        new
                        {
                            BookingId = 16L,
                            BookingDate = new DateTime(2019, 2, 5, 0, 0, 0, 0, DateTimeKind.Local),
                            FlightNo = "QA201",
                            PassengerId = 122
                        },
                        new
                        {
                            BookingId = 7L,
                            BookingDate = new DateTime(2019, 2, 4, 0, 0, 0, 0, DateTimeKind.Local),
                            FlightNo = "QA201",
                            PassengerId = 123
                        },
                        new
                        {
                            BookingId = 17L,
                            BookingDate = new DateTime(2019, 2, 5, 0, 0, 0, 0, DateTimeKind.Local),
                            FlightNo = "QA201",
                            PassengerId = 124
                        },
                        new
                        {
                            BookingId = 8L,
                            BookingDate = new DateTime(2019, 2, 5, 0, 0, 0, 0, DateTimeKind.Local),
                            FlightNo = "VM24",
                            PassengerId = 125
                        },
                        new
                        {
                            BookingId = 18L,
                            BookingDate = new DateTime(2019, 2, 6, 0, 0, 0, 0, DateTimeKind.Local),
                            FlightNo = "QA201",
                            PassengerId = 126
                        },
                        new
                        {
                            BookingId = 9L,
                            BookingDate = new DateTime(2019, 2, 5, 0, 0, 0, 0, DateTimeKind.Local),
                            FlightNo = "VM24",
                            PassengerId = 127
                        },
                        new
                        {
                            BookingId = 19L,
                            BookingDate = new DateTime(2019, 2, 7, 0, 0, 0, 0, DateTimeKind.Local),
                            FlightNo = "QA11",
                            PassengerId = 128
                        },
                        new
                        {
                            BookingId = 10L,
                            BookingDate = new DateTime(2019, 2, 5, 0, 0, 0, 0, DateTimeKind.Local),
                            FlightNo = "QA201",
                            PassengerId = 129
                        },
                        new
                        {
                            BookingId = 20L,
                            BookingDate = new DateTime(2019, 2, 7, 0, 0, 0, 0, DateTimeKind.Local),
                            FlightNo = "QA201",
                            PassengerId = 130
                        });
                });

            modelBuilder.Entity("Srikaran.ARFlights.DomainEntities.Passenger", b =>
                {
                    b.Property<int>("PassengerId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("PassengerName");

                    b.HasKey("PassengerId");

                    b.ToTable("Passengers");

                    b.HasData(
                        new
                        {
                            PassengerId = 111,
                            PassengerName = "Steven"
                        },
                        new
                        {
                            PassengerId = 112,
                            PassengerName = "Adrian"
                        },
                        new
                        {
                            PassengerId = 113,
                            PassengerName = "John"
                        },
                        new
                        {
                            PassengerId = 114,
                            PassengerName = "Ella"
                        },
                        new
                        {
                            PassengerId = 115,
                            PassengerName = "Chris"
                        },
                        new
                        {
                            PassengerId = 116,
                            PassengerName = "Rayna"
                        },
                        new
                        {
                            PassengerId = 117,
                            PassengerName = "Ada"
                        },
                        new
                        {
                            PassengerId = 118,
                            PassengerName = "Brian"
                        },
                        new
                        {
                            PassengerId = 119,
                            PassengerName = "Devon"
                        },
                        new
                        {
                            PassengerId = 120,
                            PassengerName = "Joy"
                        },
                        new
                        {
                            PassengerId = 121,
                            PassengerName = "Luke"
                        },
                        new
                        {
                            PassengerId = 122,
                            PassengerName = "Mohammad"
                        },
                        new
                        {
                            PassengerId = 123,
                            PassengerName = "Jamiya"
                        },
                        new
                        {
                            PassengerId = 124,
                            PassengerName = "Deshawn"
                        },
                        new
                        {
                            PassengerId = 125,
                            PassengerName = "Precious"
                        },
                        new
                        {
                            PassengerId = 126,
                            PassengerName = "Julie"
                        },
                        new
                        {
                            PassengerId = 127,
                            PassengerName = "Rafael"
                        },
                        new
                        {
                            PassengerId = 128,
                            PassengerName = "Zara"
                        },
                        new
                        {
                            PassengerId = 129,
                            PassengerName = "Chris"
                        },
                        new
                        {
                            PassengerId = 130,
                            PassengerName = "Jesse"
                        },
                        new
                        {
                            PassengerId = 131,
                            PassengerName = "Angelica"
                        });
                });

            modelBuilder.Entity("Srikaran.ARFlights.DomainEntities.Booking", b =>
                {
                    b.HasOne("Srikaran.ARFlights.DomainEntities.Passenger", "Passenger")
                        .WithMany()
                        .HasForeignKey("PassengerId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
